### ISSUE TITLE
How to send an class object to server socket From client socket 

### ISSUE THREAD

**Issue by swastik52** [wizzywit/Android-Socket-Programming#1]
Hi,
I want to send a class object from the client to the server. I used the bellow code but at the retrieval of an object I got NullPointer  Exception.
Code
-------
 ObjectOutputStream objOut = new ObjectOutputStream(this.clientSocket.getOutputStream());
                ObjectInputStream objectInputStream = new ObjectInputStream(this.clientSocket.getInputStream());
                emp= (EmployeeInfo) objectInputStream.readObject();

**Comment by wizzywit** [comment]
Have you tried debugging your code @swastik52
